SELECT count(T_MEMB.AGE) AS CNT_AGE, T_MEMB.AGE
FROM members AS T_MEMB
GROUP BY T_MEMB.AGE;

SELECT count(T_MEMB.AGE) AS CNT_AGE, T_MEMB.AGE
FROM members AS T_MEMB
GROUP BY T_MEMB.AGE
HAVING count(T_MEMB.AGE) >= 2;

select *
FROM (SELECT count(T_MEMB.AGE) AS CNT_AGE, T_MEMB.AGE
	FROM members AS T_MEMB
	GROUP BY T_MEMB.AGE) AS T_INNER_MEMB
WHERE T_INNER_MEMB.CNT_AGE >=2;

-- HAVING은 GROUP BY의 WHERE이다. 위 3개의 코드는 다 같은 값을 출력. HAVING도 WHERE절이기 때문에 AND 조건을 사용할 수 있다.