-- SELECT T_MEMS.*, T_MEMS_LOG.EMAIL   
-- FROM (members AS T_MEMS 
-- 	INNER JOIN members_login AS T_MEMS_LOG  
--     ON T_MEMS .MEMBERS_ID = T_MEMS_LOG.MEMBERS_ID) AS T_JOIN_MEMS_LOG  ;

    SELECT T_MEMS.*, T_MEMS_LOG.EMAIL, T_GENDER.GENDER
    FROM ( 
			members AS T_MEMS 
			INNER JOIN members_login AS T_MEMS_LOG  
			ON T_MEMS .MEMBERS_ID = T_MEMS_LOG.MEMBERS_ID
            AND T_MEMS .MEMBERS_ID ='M-01'
            )
		INNER JOIN gender_code AS T_GENDER 
		ON T_MEMS.GENDER_CODE_ID = T_GENDER.GENDER_CODE_ID  ;
	