
CREATE TABLE CHART
(
  NAME           VARCHAR(50) NOT NULL COMMENT '이름',
  AGE            INTEGER     NOT NULL COMMENT '나이',
  HEIGHT         INTEGER     NOT NULL COMMENT '키',
  WEIGHT         INTEGER     NOT NULL COMMENT '체중',
  PRESSURE       INTEGER     NOT NULL COMMENT '혈압',
  GLUCOSE        INTEGER     NOT NULL COMMENT '혈당',
  CHART_ID       VARCHAR(50) NOT NULL COMMENT '정보ID',
  GENDER_CODE    VARCHAR(50) NOT NULL COMMENT '성별ID',
  RESULT_CODE_ID VARCHAR(50) NOT NULL COMMENT '검진결과ID',
  PRIMARY KEY (CHART_ID)
) COMMENT '검진결과';

CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_CODE VARCHAR(50) NOT NULL COMMENT '성별ID',
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별코드';

CREATE TABLE NEW_ID
(
  CHART_ID    VARCHAR(50) NOT NULL COMMENT '정보ID',
  REEXAMEN_ID VARCHAR(50) NOT NULL COMMENT '재검진항목ID',
  PLAN_ID     VARCHAR(50) NOT NULL COMMENT '유지방안ID'
) COMMENT '결과매칭(ID+ID)';

CREATE TABLE PLAN
(
  PLAN    VARCHAR(50) NOT NULL COMMENT '유지방안',
  PLAN_ID VARCHAR(50) NOT NULL COMMENT '유지방안ID',
  PRIMARY KEY (PLAN_ID)
) COMMENT '유지방안';

CREATE TABLE REEXAMEN
(
  REEXAMEN    VARCHAR(50) NOT NULL COMMENT '재검진항목',
  REEXAMEN_ID VARCHAR(50) NOT NULL COMMENT '재검진항목ID',
  PRIMARY KEY (REEXAMEN_ID)
) COMMENT '재검진항목';

CREATE TABLE RESULT_CODE
(
  RESULT         VARCHAR(50) NOT NULL COMMENT '검진결과',
  RESULT_CODE_ID VARCHAR(50) NOT NULL COMMENT '검진결과ID',
  PRIMARY KEY (RESULT_CODE_ID)
) COMMENT '검진결과';

ALTER TABLE CHART
  ADD CONSTRAINT FK_GENDER_CODE_TO_CHART
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE CHART
  ADD CONSTRAINT FK_RESULT_CODE_TO_CHART
    FOREIGN KEY (RESULT_CODE_ID)
    REFERENCES RESULT_CODE (RESULT_CODE_ID);

ALTER TABLE NEW_ID
  ADD CONSTRAINT FK_CHART_TO_NEW_ID
    FOREIGN KEY (CHART_ID)
    REFERENCES CHART (CHART_ID);

ALTER TABLE NEW_ID
  ADD CONSTRAINT FK_REEXAMEN_TO_NEW_ID
    FOREIGN KEY (REEXAMEN_ID)
    REFERENCES REEXAMEN (REEXAMEN_ID);

ALTER TABLE NEW_ID
  ADD CONSTRAINT FK_PLAN_TO_NEW_ID
    FOREIGN KEY (PLAN_ID)
    REFERENCES PLAN (PLAN_ID);
