
CREATE TABLE AGE_CODE
(
  AGE         INTEGER     NOT NULL COMMENT '생산연도',
  AGE_CODE_ID VARCHAR(50) NOT NULL COMMENT '생산연도ID',
  PRIMARY KEY (AGE_CODE_ID)
) COMMENT '연식코드';

CREATE TABLE CARS
(
  CARS_ID         VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  CARS_CODE_ID    VARCHAR(50) NOT NULL COMMENT '자동차 모델별 ID',
  COMPANY_CODE_ID VARCHAR(50) NOT NULL COMMENT '회사 ID',
  AGE_CODE_ID     VARCHAR(50) NOT NULL COMMENT '생산연도ID',
  PRIMARY KEY (CARS_ID)
) COMMENT '차종류별 정보';

CREATE TABLE CARS_CODE
(
  CARS         VARCHAR(50) NOT NULL COMMENT '자동차모델',
  CARS_CODE_ID VARCHAR(50) NOT NULL COMMENT '자동차 모델별 ID',
  PRIMARY KEY (CARS_CODE_ID)
) COMMENT '자동차코드';

CREATE TABLE CARS_OPTION
(
  CAR_OPTIONS    VARCHAR(50) NOT NULL COMMENT '옵션 종류',
  CARS_OPTION_ID VARCHAR(50) NOT NULL COMMENT '옵션ID',
  PRIMARY KEY (CARS_OPTION_ID)
) COMMENT '차 옵션';

CREATE TABLE COMPANY_CODE
(
   COMPANY        VARCHAR(50) NOT NULL COMMENT '회사이름',
  COMPANY_CODE_ID VARCHAR(50) NOT NULL COMMENT '회사 ID',
  PRIMARY KEY (COMPANY_CODE_ID)
) COMMENT '회사코드';

CREATE TABLE NEW_ID
(
  CARS_ID        VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  CARS_OPTION_ID VARCHAR(50) NOT NULL COMMENT '옵션ID'
) COMMENT 'NEW ID 생성(ID+ID)';

ALTER TABLE NEW_ID
  ADD CONSTRAINT FK_CARS_TO_NEW_ID
    FOREIGN KEY (CARS_ID)
    REFERENCES CARS (CARS_ID);

ALTER TABLE NEW_ID
  ADD CONSTRAINT FK_CARS_OPTION_TO_NEW_ID
    FOREIGN KEY (CARS_OPTION_ID)
    REFERENCES CARS_OPTION (CARS_OPTION_ID);

ALTER TABLE CARS
  ADD CONSTRAINT FK_CARS_CODE_TO_CARS
    FOREIGN KEY (CARS_CODE_ID)
    REFERENCES CARS_CODE (CARS_CODE_ID);

ALTER TABLE CARS
  ADD CONSTRAINT FK_COMPANY_CODE_TO_CARS
    FOREIGN KEY (COMPANY_CODE_ID)
    REFERENCES COMPANY_CODE (COMPANY_CODE_ID);

ALTER TABLE CARS
  ADD CONSTRAINT FK_AGE_CODE_TO_CARS
    FOREIGN KEY (AGE_CODE_ID)
    REFERENCES AGE_CODE (AGE_CODE_ID);
