SELECT T_FAC.COMPANY, T_CAR_INFOR.CAR_NAME, COUNT(*) AS CNT
FROM (factorys AS T_FAC
	INNER JOIN car_infors AS T_CAR_INFOR
    ON T_FAC.COMPANY_ID = T_CAR_INFOR.COMPANY_ID)
    INNER JOIN `options` AS T_OPTS
    ON T_CAR_INFOR.CAR_INFOR_ID = T_OPTS.CAR_INFOR_ID
    GROUP BY T_FAC.COMPANY_ID, T_CAR_INFOR.CAR_INFOR_ID
    ;
    
SELECT T_FAC.COMPANY, T_CAR_INFOR.CAR_NAME, T_CAR_INFOR.CAR_INFOR_ID
FROM factorys AS T_FAC
	INNER JOIN car_infors AS T_CAR_INFOR
    ON T_FAC.COMPANY_ID = T_CAR_INFOR.COMPANY_ID
    ;
    
SELECT OPTION_INFOR_ID, OPTION_NAME
FROM option_infors;-+